config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :submissions
  resources :documents
  resources :users
  resources :aliases, only: [:index, :list] do
    collection do
      get 'list', to: 'aliases#index'
      get 'list/:id', to: 'aliases#list'
    end
  end
  root 'documents#index'

end

app/models/document.rb
# Document model
class Document < ActiveRecord::Base
  validates :file_type, presence: true, inclusion: { in: %w(zip rar tar 7z jpeg gif tiff png archive file), message: '%{value} is not a usable file.' }
  validates :digest, presence: true, length: { is: 64 }, format: { with: /\A[0-9A-Fa-f]+\z/, message: 'Not a SHA-256 digest.' }
  validates :created, presence: true
  validates :size, presence: true, numericality: { only_integer: true }

  has_many :inclusions
  has_many :aliases
  has_one :track
end

app/controllers/documents_controller.rb
# Document Controller
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white
  #  list through.
  def document_params
    params.require(:document).permit(:file_type, :digest, :created, :size, :folder)
  end

  # Use callbacks to share common setup or constraints between actions.
  #  def set_document
  #    docs = Document.where(digest: params[:id])
  #    if docs.length > 0
  #      @document = docs.first
  #    else
  #      @document = Document.new
  #    end
  #  end
end

app/helpers/documents_helper.rb
# Document Helper
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= form_for(@document) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :file_type %><br>
    <%= f.text_field :file_type %>
  </div>
  <div class="field">
    <%= f.label :digest %><br>
    <%= f.text_field :digest %>
  </div>
  <div class="field">
    <%= f.label :created %><br>
    <%= f.datetime_select :created %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :folder %><br>
    <%= f.check_box :folder %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing Document</h1>

<%= render 'form' %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Documents</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Digest</th>
      <th>Created</th>
      <th>Size</th>
      <th>Folder</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= document.file_type %></td>
        <td><%= document.digest %></td>
        <td><%= document.created %></td>
        <td><%= document.size %></td>
        <td><%= document.folder %></td>
        <td><%= link_to 'Show', document %></td>
        <td><%= link_to 'Edit', edit_document_path(document) %></td>
        <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Document', new_document_path %>

app/views/documents/new.html.erb
<h1>New Document</h1>

<%= render 'form' %>

<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @document.file_type %>
</p>

<p>
  <strong>Digest:</strong>
  <%= @document.digest %>
</p>

<p>
  <strong>Created:</strong>
  <%= @document.created %>
</p>

<p>
  <strong>Size:</strong>
  <%= @document.size %>
</p>

<p>
  <strong>Folder:</strong>
  <%= @document.folder %>
</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>