config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :submissions
  resources :documents
  resources :users
  resources :aliases, only: [:index, :list] do
    collection do
      get 'list', to: 'aliases#index'
      get 'list/:id', to: 'aliases#list'
    end
  end
  root 'documents#index'

end

app/models/submission.rb
# Submission model
class Submission < ActiveRecord::Base
  belongs_to :user
  belongs_to :submission

  validates :file_type, presence: true, inclusion: { in: %w(zip rar tar 7z jpeg gif tiff png archive file), message: '%{value} is not a usable file.' }
  validates :digest, presence: true, length: { is: 64 }, format: { with: /\A[0-9A-Fa-f]+\z/, message: 'Not a SHA-256 digest.' }
  validates :apikey, presence: true, length: { is: 64 }, format: { with: /\A[0-9A-Fa-f]+\z/, message: 'Not a valid API Key.' }
  validates :size, presence: true, numericality: { only_integer: true }
end

app/controllers/submissions_controller.rb
# Encoding: utf-8
# Submission Controller
class SubmissionsController < ApplicationController
  before_action :set_submission, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token,
                     if: proc { |c| c.request.format == 'application/json' },
                     only: [:create]
  protect_from_forgery with: :null_session,
                       if: proc { |c| c.request.format == 'application/json' }

  # GET /submissions
  # GET /submissions.json
  def index
    @submissions = Submission.all
  end

  # GET /submissions/1
  # GET /submissions/1.json
  def show
  end

  # GET /submissions/new
  def new
    @submission = Submission.new
  end

  # GET /submissions/1/edit
  def edit
  end

  # POST /submissions
  # POST /submissions.json
  def create
    respond_to do |format|
      format.html { @submission = Submission.new(submission_params) }
      format.json do
        if params.key?(:apikey) &&
           User.where(apikey: params[:apikey]).length > 0
          @submission = Submission.new
          @submission.name = params[:name]
          @submission.file_type = params[:file_type]
          @submission.digest = params[:digest]
          @submission.imageError = params[:imageError]
          @submission.modified = params[:modified]
          @submission.size = params[:size]
          @submission.height = params[:height]
          @submission.width = params[:width]
          @submission.page = params[:page]
          @submission.folder = params[:folder]
          @submission.apikey = params[:apikey]
        else
          render json: ['Invalid API Key'], status: :unprocessable_entity
          return
        end
      end
    end

    respond_to do |format|
      if @submission.save
        format.html do
          redirect_to @submission,
                      notice: 'Submission was successfully'\
                                'created.'
        end
        format.json { render :show, status: :created, location: @submission }
      else
        format.html { render :new }
        format.json do
          render json: @submission.errors,
                 status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /submissions/1
  # PATCH/PUT /submissions/1.json
  def update
    respond_to do |format|
      if @submission.update(submission_params)
        format.html do
          redirect_to @submission,
                      notice: 'Submission was successfully'\
                              'updated.'
        end
        format.json { render :show, status: :ok, location: @submission }
      else
        format.html { render :edit }
        format.json do
          render json: @submission.errors,
                 status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /submissions/1
  # DELETE /submissions/1.json
  def destroy
    @submission.destroy
    respond_to do |format|
      format.html do
        redirect_to submissions_url,
                    notice: 'Submission was successfully' \
                              'destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_submission
    @submission = Submission.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white
  # list through.
  def submission_params
    params.require(:submission).permit(:name, :file_type, :hash,
                                       :imageError, :size, :height,
                                       :width, :page, :modified,
                                       :folder, :user_id, :submission_id)
  end
end

app/helpers/submissions_helper.rb
# Submission Helper
module SubmissionsHelper
end

app/views/submissions/_form.html.erb
<%= form_for(@submission) do |f| %>
  <% if @submission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@submission.errors.count, "error") %> prohibited this submission from being saved:</h2>

      <ul>
      <% @submission.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :file_type %><br>
    <%= f.text_field :file_type %>
  </div>
  <div class="field">
    <%= f.label :hash %><br>
    <%= f.text_field :hash %>
  </div>
  <div class="field">
    <%= f.label :imageError %><br>
    <%= f.text_field :imageError %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :height %><br>
    <%= f.text_field :height %>
  </div>
  <div class="field">
    <%= f.label :width %><br>
    <%= f.text_field :width %>
  </div>
  <div class="field">
    <%= f.label :page %><br>
    <%= f.text_field :page %>
  </div>
  <div class="field">
    <%= f.label :modified %><br>
    <%= f.datetime_select :modified %>
  </div>
  <div class="field">
    <%= f.label :folder %><br>
    <%= f.check_box :folder %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :submission_id %><br>
    <%= f.text_field :submission_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/submissions/edit.html.erb
<h1>Editing Submission</h1>

<%= render 'form' %>

<%= link_to 'Show', @submission %> |
<%= link_to 'Back', submissions_path %>

app/views/submissions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Submissions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Hash</th>
      <th>Imageerror</th>
      <th>Size</th>
      <th>Height</th>
      <th>Width</th>
      <th>Page</th>
      <th>Modified</th>
      <th>Folder</th>
      <th>User</th>
      <th>Submission</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @submissions.each do |submission| %>
      <tr>
        <td><%= submission.name %></td>
        <td><%= submission.file_type %></td>
        <td><%= submission.hash %></td>
        <td><%= submission.imageError %></td>
        <td><%= submission.size %></td>
        <td><%= submission.height %></td>
        <td><%= submission.width %></td>
        <td><%= submission.page %></td>
        <td><%= submission.modified %></td>
        <td><%= submission.folder %></td>
        <td><%= submission.user %></td>
        <td><%= submission.submission %></td>
        <td><%= link_to 'Show', submission %></td>
        <td><%= link_to 'Edit', edit_submission_path(submission) %></td>
        <td><%= link_to 'Destroy', submission, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Submission', new_submission_path %>

app/views/submissions/new.html.erb
<h1>New Submission</h1>

<%= render 'form' %>

<%= link_to 'Back', submissions_path %>

app/views/submissions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @submission.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @submission.file_type %>
</p>

<p>
  <strong>Hash:</strong>
  <%= @submission.hash %>
</p>

<p>
  <strong>Imageerror:</strong>
  <%= @submission.imageError %>
</p>

<p>
  <strong>Size:</strong>
  <%= @submission.size %>
</p>

<p>
  <strong>Height:</strong>
  <%= @submission.height %>
</p>

<p>
  <strong>Width:</strong>
  <%= @submission.width %>
</p>

<p>
  <strong>Page:</strong>
  <%= @submission.page %>
</p>

<p>
  <strong>Modified:</strong>
  <%= @submission.modified %>
</p>

<p>
  <strong>Folder:</strong>
  <%= @submission.folder %>
</p>

<p>
  <strong>User:</strong>
  <%= @submission.user %>
</p>

<p>
  <strong>Submission:</strong>
  <%= @submission.submission %>
</p>

<%= link_to 'Edit', edit_submission_path(@submission) %> |
<%= link_to 'Back', submissions_path %>